### ISSUE TITLE
Sofapython3 plugin loading

### ISSUE THREAD

**Issue by lucac-crypto** [sofa-framework/SofaPython3#341] opened 2023-03-29 09:43 UTC
Hi, I have downloaded the latest version of sofa using binaries but when I try to load the plugin .dll file sofa says that it cannot find such file. I have tried using different python version and also different sofa ones but with the same result.
Can someone help me?

**Comment by alxbilger** [comment] 2023-03-29 10:01
Duplicate of #339

**Closed by alxbilger** 2023-03-29 10:01 UTC
